# sftool/variant_confirmation/matcher.py

from __future__ import annotations

import os
import subprocess
import tempfile

from pathlib import Path
from typing import Callable, Dict, List, Sequence, Tuple

import vcfpy

from sftool.variant_confirmation.models import (
    VariantCandidate,
    VariantMatch,
)


class CandidateMatcherError(RuntimeError):
    """
    Base exception for diagnostic candidate matching failures.
    """

    pass


class InvalidMatcherInputError(CandidateMatcherError):
    """
    Raised when candidates or matcher arguments are invalid.
    """

    pass


class PatientVcfError(CandidateMatcherError):
    """
    Raised when the normalized patient VCF is missing or invalid.
    """

    pass


class CandidateMatchCommandError(CandidateMatcherError):
    """
    Raised when a bcftools command fails.
    """

    pass


class CandidateMatchResultError(CandidateMatcherError):
    """
    Raised when the matching output is inconsistent or ambiguous.
    """

    pass


class CandidateMatchingOutput:
    """
    Output generated by CandidateMatcher.

    Contains one VariantMatch object for every input candidate and the path
    to the compressed VCF containing the exact patient matches.
    """

    def __init__(
            self,
            matches: List[VariantMatch],
            vcf_path: Path,
    ):
        self.matches = self._validate_matches(
            matches
        )
        self.vcf_path = self._validate_vcf_path(
            vcf_path
        )

    @staticmethod
    def _validate_matches(
            matches: List[VariantMatch],
    ) -> List[VariantMatch]:
        if not isinstance(matches, list):
            raise TypeError(
                "matches must be a list of VariantMatch objects"
            )

        for index, match in enumerate(
                matches,
                start=1,
        ):
            if not isinstance(match, VariantMatch):
                raise TypeError(
                    f"Match {index} must be a VariantMatch, "
                    f"got {type(match).__name__}"
                )

        return list(
            matches
        )

    @staticmethod
    def _validate_vcf_path(
            vcf_path: Path,
    ) -> Path:
        if not isinstance(vcf_path, Path):
            raise TypeError(
                "vcf_path must be a pathlib.Path"
            )

        return vcf_path

    def to_dict(self) -> dict:
        return {
            "matches": [
                match.to_dict()
                for match in self.matches
            ],
            "vcf_path": str(self.vcf_path),
        }

    def __repr__(self) -> str:
        return (
            "CandidateMatchingOutput("
            f"matches={len(self.matches)}, "
            f"vcf_path={str(self.vcf_path)!r})"
        )


class CandidateMatcher:
    """
    Match normalized diagnostic candidates against a normalized patient VCF.

    Matching is performed using exact equality of:

        CHROM + POS + REF + ALT

    The patient VCF must contain exactly one sample.

    Genotype, QUAL, FILTER and FORMAT values are copied into VariantMatch
    objects for informational and reporting purposes. No clinical
    interpretation of those values is performed by this component.
    """

    DEFAULT_FILENAME = "diagnostic_candidates.matches.vcf.gz"

    def __init__(
            self,
            bcftools_path: str | Path,
            runner: Callable = subprocess.run,
    ):
        self.bcftools_path = self._validate_executable_path(
            bcftools_path
        )

        if not callable(runner):
            raise TypeError(
                "runner must be callable"
            )

        self.runner = runner

    def match(
            self,
            candidates: Sequence[VariantCandidate],
            patient_vcf_path: str | Path,
            output_path: str | Path,
    ) -> CandidateMatchingOutput:
        """
        Match normalized candidates against a normalized patient VCF.

        Parameters
        ----------
        candidates
            Non-empty sequence of normalized VariantCandidate objects.
        patient_vcf_path
            Normalized, bgzip-compressed, single-sample patient VCF.
        output_path
            Destination path for the compressed exact-match VCF.

        Returns
        -------
        CandidateMatchingOutput
            Matching results and path to the generated match VCF.

        Raises
        ------
        InvalidMatcherInputError
            If the candidate collection is invalid.
        PatientVcfError
            If the patient VCF is invalid or is not single-sample.
        CandidateMatchCommandError
            If a bcftools command fails.
        CandidateMatchResultError
            If the generated matching output is inconsistent.
        """
        validated_candidates = self._validate_candidates(
            candidates
        )

        patient_vcf_path = self._validate_patient_vcf_path(
            patient_vcf_path
        )

        output_path = self._validate_output_path(
            output_path
        )

        output_path.parent.mkdir(
            parents=True,
            exist_ok=True,
        )

        sample_name = self._get_single_sample_name(
            patient_vcf_path
        )

        candidate_by_key = self._build_candidate_key_index(
            validated_candidates
        )

        matches_by_id = self._initialize_matches(
            validated_candidates
        )

        self._ensure_patient_vcf_index(
            patient_vcf_path
        )

        final_index_path = Path(
            f"{output_path}.tbi"
        )

        try:
            with tempfile.TemporaryDirectory(
                    prefix=".diagnostic_candidate_matching.",
                    dir=output_path.parent,
            ) as temporary_directory:
                temporary_directory = Path(
                    temporary_directory
                )

                regions_path = (
                        temporary_directory
                        / "candidate_regions.tsv"
                )

                regional_vcf_path = (
                        temporary_directory
                        / "candidate_regions.vcf"
                )

                exact_vcf_path = (
                        temporary_directory
                        / "diagnostic_candidates.matches.vcf"
                )

                temporary_output_path = (
                        temporary_directory
                        / self.DEFAULT_FILENAME
                )

                temporary_index_path = Path(
                    f"{temporary_output_path}.tbi"
                )

                self._write_regions_file(
                    candidates=validated_candidates,
                    output_path=regions_path,
                )

                self._extract_candidate_regions(
                    patient_vcf_path=patient_vcf_path,
                    regions_path=regions_path,
                    output_path=regional_vcf_path,
                )

                self._filter_exact_matches(
                    regional_vcf_path=regional_vcf_path,
                    output_path=exact_vcf_path,
                    sample_name=sample_name,
                    candidate_by_key=candidate_by_key,
                    matches_by_id=matches_by_id,
                )

                self._add_not_found_warnings(
                    matches_by_id
                )

                self._compress_vcf(
                    input_path=exact_vcf_path,
                    output_path=temporary_output_path,
                )

                self._index_vcf(
                    temporary_output_path
                )

                self._validate_generated_outputs(
                    vcf_path=temporary_output_path,
                    index_path=temporary_index_path,
                )

                os.replace(
                    temporary_output_path,
                    output_path,
                )

                os.replace(
                    temporary_index_path,
                    final_index_path,
                )

        except CandidateMatcherError:
            raise

        except OSError as exc:
            raise CandidateMatchResultError(
                "Could not finalize diagnostic candidate match VCF "
                f"{output_path}: {exc}"
            ) from exc

        ordered_matches = [
            matches_by_id[candidate.candidate_id]
            for candidate in validated_candidates
        ]

        return CandidateMatchingOutput(
            matches=ordered_matches,
            vcf_path=output_path,
        )

    def match_to_directory(
            self,
            candidates: Sequence[VariantCandidate],
            patient_vcf_path: str | Path,
            output_directory: str | Path,
            filename: str = DEFAULT_FILENAME,
    ) -> CandidateMatchingOutput:
        """
        Match candidates using the standard SFtool output filename.
        """
        output_directory = self._validate_output_directory(
            output_directory
        )

        filename = self._validate_filename(
            filename
        )

        return self.match(
            candidates=candidates,
            patient_vcf_path=patient_vcf_path,
            output_path=output_directory / filename,
        )

    def _validate_candidates(
            self,
            candidates: Sequence[VariantCandidate],
    ) -> List[VariantCandidate]:
        """
        Validate candidates before matching.
        """
        if isinstance(candidates, (str, bytes)):
            raise InvalidMatcherInputError(
                "candidates must be a sequence of VariantCandidate objects"
            )

        if not isinstance(candidates, Sequence):
            raise InvalidMatcherInputError(
                "candidates must be a sequence of VariantCandidate objects"
            )

        candidates = list(
            candidates
        )

        if not candidates:
            raise InvalidMatcherInputError(
                "At least one diagnostic variant candidate is required"
            )

        candidate_ids = set()
        matching_keys = set()

        for index, candidate in enumerate(
                candidates,
                start=1,
        ):
            if not isinstance(candidate, VariantCandidate):
                raise InvalidMatcherInputError(
                    f"Candidate {index} must be a VariantCandidate, "
                    f"got {type(candidate).__name__}"
                )

            if not candidate.is_normalized():
                raise InvalidMatcherInputError(
                    f"Candidate {candidate.candidate_id!r} "
                    "has not been normalized"
                )

            if candidate.candidate_id in candidate_ids:
                raise InvalidMatcherInputError(
                    "Candidate IDs must be unique; duplicated ID: "
                    f"{candidate.candidate_id}"
                )

            matching_key = candidate.get_matching_key()

            if matching_key in matching_keys:
                raise InvalidMatcherInputError(
                    "Normalized diagnostic candidates must be unique; "
                    "duplicated variant: "
                    f"{candidate.get_normalized_variant()}"
                )

            candidate_ids.add(
                candidate.candidate_id
            )

            matching_keys.add(
                matching_key
            )

        return candidates

    @staticmethod
    def _validate_patient_vcf_path(
            patient_vcf_path: str | Path,
    ) -> Path:
        """
        Validate the normalized patient VCF path.
        """
        if not isinstance(patient_vcf_path, (str, Path)):
            raise TypeError(
                "patient_vcf_path must be a string or pathlib.Path"
            )

        patient_vcf_path = Path(
            patient_vcf_path
        )

        if not patient_vcf_path.is_file():
            raise FileNotFoundError(
                f"Normalized patient VCF not found: {patient_vcf_path}"
            )

        if not patient_vcf_path.name.endswith(".vcf.gz"):
            raise PatientVcfError(
                "Normalized patient VCF must use the .vcf.gz extension"
            )

        return patient_vcf_path

    @staticmethod
    def _validate_output_path(
            output_path: str | Path,
    ) -> Path:
        """
        Validate the final match VCF output path.
        """
        if not isinstance(output_path, (str, Path)):
            raise TypeError(
                "output_path must be a string or pathlib.Path"
            )

        output_path = Path(
            output_path
        )

        if not output_path.name:
            raise ValueError(
                "output_path must include a filename"
            )

        if not output_path.name.endswith(".vcf.gz"):
            raise ValueError(
                "Candidate match VCF output must use the .vcf.gz extension"
            )

        return output_path

    @staticmethod
    def _validate_output_directory(
            output_directory: str | Path,
    ) -> Path:
        """
        Validate a workflow output directory.
        """
        if not isinstance(output_directory, (str, Path)):
            raise TypeError(
                "output_directory must be a string or pathlib.Path"
            )

        return Path(
            output_directory
        )

    @staticmethod
    def _validate_filename(
            filename: str,
    ) -> str:
        """
        Validate the standard output filename.
        """
        if not isinstance(filename, str):
            raise TypeError(
                "filename must be a string"
            )

        filename = filename.strip()

        if not filename:
            raise ValueError(
                "filename must be a non-empty string"
            )

        if Path(filename).name != filename:
            raise ValueError(
                "filename must not contain directory components"
            )

        if not filename.endswith(".vcf.gz"):
            raise ValueError(
                "Candidate match VCF filename must use the .vcf.gz extension"
            )

        return filename

    @staticmethod
    def _validate_executable_path(
            bcftools_path: str | Path,
    ) -> Path:
        """
        Validate the bcftools executable.
        """
        if not isinstance(bcftools_path, (str, Path)):
            raise TypeError(
                "bcftools_path must be a string or pathlib.Path"
            )

        bcftools_path = Path(
            bcftools_path
        )

        if not bcftools_path.is_file():
            raise FileNotFoundError(
                f"bcftools executable not found: {bcftools_path}"
            )

        if not os.access(
                bcftools_path,
                os.X_OK,
        ):
            raise PermissionError(
                f"bcftools is not executable: {bcftools_path}"
            )

        return bcftools_path

    @staticmethod
    def _build_candidate_key_index(
            candidates: Sequence[VariantCandidate],
    ) -> Dict[
        Tuple[str, int, str, str],
        VariantCandidate
    ]:
        """
        Index candidates by normalized CHROM, POS, REF and ALT.
        """
        return {
            candidate.get_matching_key(): candidate
            for candidate in candidates
        }

    @staticmethod
    def _initialize_matches(
            candidates: Sequence[VariantCandidate],
    ) -> Dict[str, VariantMatch]:
        """
        Create one not-found VariantMatch for every candidate.
        """
        return {
            candidate.candidate_id: VariantMatch(
                candidate_id=candidate.candidate_id,
                chromosome=candidate.normalized_chromosome,
                position=candidate.normalized_position,
                reference=candidate.normalized_reference,
                alternate=candidate.normalized_alternate,
                found=False,
            )
            for candidate in candidates
        }

    @staticmethod
    def _get_single_sample_name(
            patient_vcf_path: Path,
    ) -> str:
        """
        Return the only sample declared in the patient VCF.
        """
        reader = None

        try:
            reader = vcfpy.Reader.from_path(
                str(patient_vcf_path)
            )

            sample_names = list(
                reader.header.samples.names
            )

        except Exception as exc:
            raise PatientVcfError(
                "Could not read normalized patient VCF header "
                f"{patient_vcf_path}: {exc}"
            ) from exc

        finally:
            if reader is not None:
                reader.close()

        if not sample_names:
            raise PatientVcfError(
                "Normalized patient VCF contains no sample columns"
            )

        if len(sample_names) != 1:
            raise PatientVcfError(
                "Normalized patient VCF must contain exactly one sample; "
                f"found {len(sample_names)} samples: "
                + ", ".join(sample_names)
            )

        return sample_names[0]

    def _ensure_patient_vcf_index(
            self,
            patient_vcf_path: Path,
    ) -> None:
        """
        Create a tabix index when the patient VCF is not already indexed.
        """
        tbi_path = Path(
            f"{patient_vcf_path}.tbi"
        )

        csi_path = Path(
            f"{patient_vcf_path}.csi"
        )

        if tbi_path.is_file() or csi_path.is_file():
            return

        self._run_command(
            [
                str(self.bcftools_path),
                "index",
                "--tbi",
                str(patient_vcf_path),
            ],
            operation="index normalized patient VCF",
        )

        if not tbi_path.is_file() and not csi_path.is_file():
            raise CandidateMatchResultError(
                "bcftools completed without creating an index for "
                f"{patient_vcf_path}"
            )

    @staticmethod
    def _write_regions_file(
            candidates: Sequence[VariantCandidate],
            output_path: Path,
    ) -> None:
        """
        Write unique normalized candidate positions for regional extraction.

        bcftools region files use one-based inclusive coordinates.
        """
        positions = {
            (
                candidate.normalized_chromosome,
                candidate.normalized_position,
            )
            for candidate in candidates
        }

        try:
            with output_path.open(
                    "w",
                    encoding="utf-8",
                    newline="\n",
            ) as regions_file:
                for chromosome, position in sorted(
                        positions,
                        key=lambda value: (
                                value[0],
                                value[1],
                        ),
                ):
                    regions_file.write(
                        f"{chromosome}\t{position}\t{position}\n"
                    )

        except OSError as exc:
            raise CandidateMatchResultError(
                "Could not write candidate regions file "
                f"{output_path}: {exc}"
            ) from exc

    def _extract_candidate_regions(
            self,
            patient_vcf_path: Path,
            regions_path: Path,
            output_path: Path,
    ) -> None:
        """
        Extract patient records located at candidate positions.

        Exact REF and ALT filtering is performed afterwards in Python.
        """
        self._run_command(
            [
                str(self.bcftools_path),
                "view",
                "--regions-file",
                str(regions_path),
                "--output-type",
                "v",
                "--output",
                str(output_path),
                str(patient_vcf_path),
            ],
            operation="extract candidate regions from patient VCF",
        )

        if not output_path.is_file():
            raise CandidateMatchResultError(
                "bcftools completed without creating the regional VCF: "
                f"{output_path}"
            )

    def _filter_exact_matches(
            self,
            regional_vcf_path: Path,
            output_path: Path,
            sample_name: str,
            candidate_by_key: Dict[
                Tuple[str, int, str, str],
                VariantCandidate
            ],
            matches_by_id: Dict[str, VariantMatch],
    ) -> None:
        """
        Retain only exact CHROM, POS, REF and ALT matches.

        Genotype, QUAL, FILTER and FORMAT information is copied into the
        corresponding VariantMatch for later reporting.
        """
        reader = None
        writer = None

        seen_matching_keys = set()

        try:
            reader = vcfpy.Reader.from_path(
                str(regional_vcf_path)
            )

            writer = vcfpy.Writer.from_path(
                str(output_path),
                reader.header,
            )

            for record in reader:
                matching_candidates = []

                for alternate in record.ALT:
                    alternate_value = str(
                        alternate.value
                    ).upper()

                    matching_key = (
                        record.CHROM,
                        int(record.POS),
                        record.REF.upper(),
                        alternate_value,
                    )

                    candidate = candidate_by_key.get(
                        matching_key
                    )

                    if candidate is None:
                        continue

                    if matching_key in seen_matching_keys:
                        raise CandidateMatchResultError(
                            "Multiple patient VCF records match "
                            f"candidate {candidate.candidate_id!r}: "
                            f"{candidate.get_normalized_variant()}"
                        )

                    seen_matching_keys.add(
                        matching_key
                    )

                    matching_candidates.append(
                        candidate
                    )

                if not matching_candidates:
                    continue

                writer.write_record(
                    record
                )

                sample_call = record.call_for_sample.get(
                    sample_name
                )

                if sample_call is None:
                    raise PatientVcfError(
                        "Could not retrieve sample information for "
                        f"{sample_name!r}"
                    )

                genotype = sample_call.data.get(
                    "GT"
                )

                sample_format = dict(
                    sample_call.data
                )

                quality = (
                    float(record.QUAL)
                    if record.QUAL is not None
                    else None
                )

                filters = self._normalize_filters(
                    record.FILTER
                )

                for candidate in matching_candidates:
                    variant_match = matches_by_id[
                        candidate.candidate_id
                    ]

                    variant_match.set_match_data(
                        genotype=genotype,
                        quality=quality,
                        filters=filters,
                        sample_format=sample_format,
                    )

                    self._add_informational_warnings(
                        variant_match=variant_match,
                    )

        except CandidateMatcherError:
            raise

        except Exception as exc:
            raise CandidateMatchResultError(
                "Could not process regional patient VCF "
                f"{regional_vcf_path}: "
                f"{regional_vcf_path}: {exc}"
            ) from exc

        finally:
            if writer is not None:
                writer.close()

            if reader is not None:
                reader.close()

    @staticmethod
    def _normalize_filters(
            filters,
    ) -> List[str]:
        """
        Convert VCF FILTER values into a stable list of strings.
        """
        if filters is None:
            return []

        return [
            str(filter_value)
            for filter_value in filters
            if (
                    filter_value is not None
                    and str(filter_value) not in {"", "."}
            )
        ]

    @staticmethod
    def _add_informational_warnings(
            variant_match: VariantMatch,
    ) -> None:
        """
        Add non-blocking warnings derived from informational VCF fields.
        """
        if (
                variant_match.filters
                and variant_match.filters != ["PASS"]
        ):
            variant_match.add_warning(
                "Matched variant does not pass the patient VCF filters: "
                + ", ".join(variant_match.filters)
            )

        if CandidateMatcher._is_missing_genotype(
                variant_match.genotype
        ):
            variant_match.add_warning(
                "Matched variant has no callable genotype"
            )

    @staticmethod
    def _is_missing_genotype(
            genotype: str | None,
    ) -> bool:
        """
        Return True when the GT field contains no callable alleles.
        """
        if genotype is None:
            return True

        genotype = str(
            genotype
        ).strip()

        return genotype in {
            "",
            ".",
            "./.",
            ".|.",
        }

    @staticmethod
    def _add_not_found_warnings(
            matches_by_id: Dict[str, VariantMatch],
    ) -> None:
        """
        Add a warning to candidates absent from the normalized patient VCF.
        """
        for variant_match in matches_by_id.values():
            if variant_match.found:
                continue

            variant_match.add_warning(
                "Diagnostic variant candidate was not found in the "
                "normalized patient VCF"
            )

    def _compress_vcf(
            self,
            input_path: Path,
            output_path: Path,
    ) -> None:
        """
        Bgzip-compress the exact-match VCF.
        """
        self._run_command(
            [
                str(self.bcftools_path),
                "view",
                "--output-type",
                "z",
                "--output",
                str(output_path),
                str(input_path),
            ],
            operation="compress diagnostic candidate match VCF",
        )

    def _index_vcf(
            self,
            vcf_path: Path,
    ) -> None:
        """
        Create the tabix index for the match VCF.
        """
        self._run_command(
            [
                str(self.bcftools_path),
                "index",
                "--tbi",
                str(vcf_path),
            ],
            operation="index diagnostic candidate match VCF",
        )

    @staticmethod
    def _validate_generated_outputs(
            vcf_path: Path,
            index_path: Path,
    ) -> None:
        """
        Ensure both final artifacts were generated.
        """
        if not vcf_path.is_file():
            raise CandidateMatchResultError(
                "Diagnostic candidate match VCF was not generated: "
                f"{vcf_path}"
            )

        if not index_path.is_file():
            raise CandidateMatchResultError(
                "Diagnostic candidate match VCF index was not generated: "
                f"{index_path}"
            )

    def _run_command(
            self,
            command: List[str],
            operation: str,
    ) -> None:
        """
        Execute a bcftools command and convert failures to domain errors.
        """
        try:
            self.runner(
                command,
                check=True,
                capture_output=True,
                text=True,
            )

        except subprocess.CalledProcessError as exc:
            stderr = (
                exc.stderr.strip()
                if exc.stderr
                else "No stderr output"
            )

            raise CandidateMatchCommandError(
                f"Could not {operation}.\n"
                f"Command: {' '.join(command)}\n"
                f"Exit status: {exc.returncode}\n"
                f"Error: {stderr}"
            ) from exc

        except OSError as exc:
            raise CandidateMatchCommandError(
                "Could not execute bcftools while attempting to "
                f"{operation}: {exc}"
            ) from exc